# Generated by Django 2.2.7 on 2019-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
