# Generated by Django 2.2.7 on 2019-11-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_auto_20191122_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='file',
            new_name='files',
        ),
    ]
