# Generated by Django 2.2.7 on 2019-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0003_auto_20191124_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isFile',
            field=models.BooleanField(default=False),
        ),
    ]
