# Generated by Django 2.2.7 on 2019-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0004_blog_isfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
