# Generated by Django 2.2.7 on 2019-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyun', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_jun',
            new_name='Blog_hyun',
        ),
    ]
